### ISSUE TITLE
^w no longer works in insert mode

### ISSUE THREAD

**Issue by jeaye** [GermainZ/weechat-vimode#14]
In vim, ^w can still be used (to delete back a word), as can ^u (to delete to hard-beginning). These work in weechat without vim mode, but no longer work when it's enabled. I think they should still function normally.

**Comment by jeaye** [comment]
I found this was caused by allowing vim mode to change my bindings. I saw the meta changes, but missed this one as well. Since I'm not sure why this one was changed, I've reset it for now. I'll leave this open, in case you have some more info.

**Comment by jeaye** [comment]
I see why this was caused, though it wasn't clear when setting this up (window commands use ^w). Perhaps some more documentation on this would help.

**Comment by GermainZ** [comment]
`^U` should still work as intended. `^W` can be bound again by weechat-vimode, would that solve the issue?

**Comment by jeaye** [comment]
Yeah, I reset ^w to fix that. ^u does work in insert mode and goes up half a page in normal mode, as expected. I'm not sure what I was thinking. Closing.

**Comment by GermainZ** [comment]
`^W` will now be bound to `/input delete_last_word` when running `/vimode bind_keys` (d2321fed6ce72973f1a2b4a9280bb36a6632d9ef).
