### ISSUE TITLE
^j and ^k in normal mode

### ISSUE THREAD

**Issue by jeaye** [GermainZ/weechat-vimode#15]
I've bound ^j and ^k to `/buffer +1` and `-1` and they work fine in insert mode. In normal mode, they do nothing. gt and gT, however, work fine in normal mode. Can ^j and ^k work?

**Comment by GermainZ** [comment]
Currently, `K` and `J` are bound to `/buffer +1` and `/buffer -1` respectively (same with `gt` and `gT`; this may look inverted to some users, depending on the position of the buffers bar for you…). At the moment, you can bind ^J and ^K by editing the vimode.py script (see lines 754-757; you want to bind `\x01J` and `\x01K`).

**Comment by jeaye** [comment]
Yeah, I saw that K and J were bound to it. To fit my usual vim setup, I'm trying for ^j and ^k though. I'll take a look at the script and see if I can't get it to work without patching. Thanks for the update.

**Comment by jeaye** [comment]
Do you have plans to expose a way of binding these through vimode?

**Comment by GermainZ** [comment]
Please check #20 out.
