### ISSUE TITLE
^^ doesn't follow vim

### ISSUE THREAD

**Issue by jeaye** [GermainZ/weechat-vimode#18]
In vim `^^` will switch back and forth between two buffers. In weechat, it looks like you *meant* for it to do that, but it actually just jumps to the **last** buffer unconditionally (that is, the buffer with the highest number). To fix this, I have rebound it. I think we should do this by default.

`ctrl-^ => /input jump_last_buffer_displayed`

**Comment by GermainZ** [comment]
Thanks, fixed in e536552fe51f38e608dafc28e41e26e86bb05568. You may need to rebind the key yourself for it to work correctly in Insert mode (the normal WeeChat mode).
