### ISSUE TITLE
Feature request: C

### ISSUE THREAD

**Issue by jeaye** [GermainZ/weechat-vimode#19]
For single-line editing `C` would be really great. We currently have `c$`, which does the trick, but isn't generally what someone would type, I think.

**Comment by GermainZ** [comment]
Added `C` and `D` in d4b260b. Not adding `Y` just yet until I can think about https://github.com/GermainZ/weechat-vimode/issues/15#issuecomment-72576202, so that it can be binded to y$ if necessary.

**Comment by jeaye** [comment]
Badass. Thanks for all the help.
