### ISSUE TITLE
Custom key bindings (discussion/testing required)

### ISSUE THREAD

**Issue by GermainZ** [GermainZ/weechat-vimode#20]
Hey guys,

I'm going to use the [custom-mappings](https://github.com/GermainZ/weechat-vimode/tree/custom-mappings) branch to test custom key bindings support. It is currently possible to map keys by editing line 764:

> USER_VI_KEYS = {'Y': "y$", 'gb': ":b"}

This will map `Y` to `y$`, and `gb` to `:b` (`2gb` will execute `:b 2`).

It's a test branch because I'd like to know what people would actually like to see in weechat-vimode, because I don't think 100% vim-support (e.g. `<CR>`) makes sense for an IRC client (but if someone thinks otherwise, then I'll look into it).

Please test it and see if there's anything extra you'd like to see, or if there are any bugs.

PS. I definitely plan to expose this through commands (`:map`), editing `vimode.py` is only temporary.

Thanks. :)

**Comment by jeaye** [comment]
I certainly don't think 100% vim support is necessary. I'd never, for example, care to use macros while editing IRC. Plugins... maybe, but that's a whole different ball game.

Given the current state of this plugin, my biggest gripe is that I can't have my keybindings match the rest of my environment (vim, firefox, cmus, apvlv, etc).

After that, the thing I'd likely want most is tab support (like vim's TUI tabs) for servers or buffers. Ideally, I could have a tab for each server and then buffers.pl, in that tab, would should only the buffers for that server. This is likely way outside the scope of this plugin, but it puts into perspective that I think things are in a stable state once we get #20 worked out.

Now, onto #20. When I specify this in my vimode.py (checked out e24c6783b15ccb3f30189af7a0bf4b27d717588f):
```python
USER_VI_KEYS = {'Y': "y$", 'gb': ":b", '\x01J': "/buffer +1", '\x01K': "/buffer -1"}
```
and reload vimode in weechat (where ctrl-J and ctrl-K are unbound in my settings):
```
/script reload vimode
```
I'm unable to use either key combo in insert or normal mode for switching buffers. Can you tests these keys on your end?

**Comment by GermainZ** [comment]
Mapping to WeeChat commands should be supported now. Of course, this means you can't have another key search (`/`), but I think that's an acceptable compromise.

**Comment by jeaye** [comment]
I'm not sure what you mean about `/`. I've pulled the latest and neither ^j ^k have any functionality in normal or insert mode (I see in the script they're supposed to switch buffers). Are they working for you? I'm in tmux, urxvt, and Arch Linux.

**Comment by GermainZ** [comment]
`/` is typically used for searching.

Are you sure you're on the correct branch and got [this](https://github.com/GermainZ/weechat-vimode/commit/9da8fe2a9cb06a44cc94dfde5941406b139b702a) commit? It's all working fine for me (I'm not using urxvt, though).

**Comment by jeaye** [comment]
I know `/` is used for searching. What does it have to do with this issue?

Yes, I'm on the correct branch. Yes, I'm running on 9da8fe2a9cb06a44cc94dfde5941406b139b702a.

**Comment by jeaye** [comment]
I have tested: neither `^j` nor `^k` work in xterm either. Perhaps it's related to tmux?

**Comment by GermainZ** [comment]
> I know `/` is used for searching. What does it have to do with this issue?

In vim, binding `KEY` to `/something` will search for `something`. In weechat-vimode, binding `KEY` to `/something` will execute the WeeChat command `/something`.

> I have tested: neither ^j nor ^k work in xterm either. Perhaps it's related to tmux?
> Edit:
> Verified, these don't work without tmux either.

Working fine for me, with and without tmux, in and outside urxvt. Not sure what's happening here -- can you try to debug it quickly (by adding `print` statements where it makes sense) if you're familiar with Python?

**Comment by jeaye** [comment]
> In vim, binding KEY to /something will search for something. In weechat-vimode, binding KEY to /something will execute the WeeChat command /something.

Ah, right. Makes sense, thank you.

> can you try to debug it quickly (by adding print statements where it makes sense) if you're familiar with Python?

I can invest some time perhaps tonight, if not this weekend.

**Comment by GermainZ** [comment]
When you find the time, feel free to ping me on IRC (GermainZ on freenode) as that would make communication easier.

**Comment by artur-shaik** [comment]
Do I already can map jk to Esc?

**Comment by GermainZ** [comment]
No, that's not possible right now. weechat-vimode doesn't modify bindings in Insert mode.
On Sun, Mar 08, 2015 at 4:44 PM, Artur Shaik <notifications@github.com> wrote:Do I already can map jk to Esc?

**Comment by GermainZ** [comment]
As of 6c881f0f060a8a2dbb8135d5f1d6db70ca91dda3, user-defined key mappings are now possible via `:nmap` and `:nunmap`.
