### ISSUE TITLE
Multi-line paste from insert mode doesn't just paste

### ISSUE THREAD

**Issue by jeaye** [GermainZ/weechat-vimode#21]
When in insert mode, if I paste multiple lines (I'm prompted to paste, then I choose to), I end up getting switched to the next buffer below and not all of the paste ends up going in, as though it's treating the paste as vim commands.

**Comment by GermainZ** [comment]
I can't reproduce this. Please post the exact steps to reproduce this (including which keys you press to paste, confirm, etc), the terminal(+multiplexer?) you're using, and the value of the following config:

    weechat.look.paste_bracketed
    weechat.look.paste_max_lines

**Comment by jeaye** [comment]
This appears to be unrelated to vimode, since it happens when I disable vimode from autoload and start weechat fresh. I'm closing this and I'll be taking this up with the weechat devs directly instead. Thanks.
