### ISSUE TITLE
Allow buffer switch with :b<number>

### ISSUE THREAD

**Issue by DarkDefender** [GermainZ/weechat-vimode#22]
Currently you have to type :b\<space\>\<number\>. I use the :b\<number\> feature quite often in vim so I would be really happy if vimode would support this also.

I don't know how the current code works. But to support this, I guess one could just check if the first letter after ":" is b and the rest of the string is a number.

**Comment by GermainZ** [comment]
You can use `:b <number>` for the time being. Note the space.

**Comment by DarkDefender** [comment]
Yes, I know. I typed \< without the backslash first so it was hard to read what i meant because github removed everything withing the \<\> area

**Comment by loiclefloch** [comment]
+1 it would be a great feature

**Comment by GermainZ** [comment]
This is now possible, see #28.
