### ISSUE TITLE
Allow switching to and / or scrolling of nick list.

### ISSUE THREAD

**Issue by mkevins** [GermainZ/weechat-vimode#26]
For channels with a large number of users, the nick list only shows the top part of the alphabetical list. It would be nice to be able to scroll this list using vimode.

Maybe this could be accomplished by switching to the nick list, then normal j,k scrolling? Can it just be treated as another buffer?

Not sure how one would switch to it.. maybe ctrl-w [something]?

**Comment by GermainZ** [comment]
>Maybe this could be accomplished by switching to the nick list, then normal j,k scrolling? Can it just be treated as another buffer?
>Not sure how one would switch to it.. maybe ctrl-w [something]?

Too many cases to consider IMO: nicklist visibility, position (`^W→`, `^W←`, `^W↑` or `^W↓`? `j`/`k` or `h`/`l`?) and bar filling direction.

WeeChat already offers `F11` and `F12` to scroll the nicklist. That won't work in weechat-vimode's normal mode, but alternative (or the same) key bindings can be offered for next/previous nicklist pages. `nT` and `nt`, maybe (similar to `gT` and `gt`)?

**Comment by mkevins** [comment]
Those would be an improvement over not being able to see nicks without using the "names" command. I like nt and nT if there are no other conflicts with that, because 'n' is a very accessible key, and it is on the right hand (with 't' being on the left, this makes it even faster).

**Comment by GermainZ** [comment]
Added in b7047257836c6100893e2fa36649214d6e1bae9c :)

**Comment by mkevins** [comment]
Great to hear! Thanks for implementing that.
