### ISSUE TITLE
Are Shift + J and Shift + K backwards?

### ISSUE THREAD

**Issue by willhoag** [GermainZ/weechat-vimode#31]
`Shift + K` to go to the next buffer and `Shift + J` to go to the previous buffer seems backwards to me. Shouldn't `J` go down a buffer and `K` go up a buffer?

**Comment by keith** [comment]
Related: https://github.com/GermainZ/weechat-vimode/pull/30

**Comment by willhoag** [comment]
Seems like enough people are looking for a proper solution to this. Any updates?

**Comment by GermainZ** [comment]
You can manually flip them for now. Just edit ~/.weechat/python/vimode.py and modify these lines (lines 785-788):

           'gt': "/buffer +1",
           'K': "/buffer +1",
           'gT': "/buffer -1",
           'J': "/buffer -1",

… to:

           'gt': "/buffer -1",
           'K': "/buffer -1",
           'gT': "/buffer +1",
           'J': "/buffer +1",

… then reload the script in WeeChat:

    /script reload vimode

**Comment by GermainZ** [comment]
Actually, I think I've been wrong about this. J/K seem to be always flipped regardless of bar orientation, so I think I'll flip them by default.

**Comment by willhoag** [comment]
Cool. It looked like there was already a pull request that made the change, so I'll forgo offering to make one. Will manually flip them in the mean time. Thanks!

![thanks](http://i.giphy.com/3oEdva9BUHPIs2SkGk.gif)

**Comment by GermainZ** [comment]
Done in 7c8ae03f19ccf59358bd86325e5353c07edb018f :)
