### ISSUE TITLE
Change search key binding ('search_text' vs. 'search_text_here')

### ISSUE THREAD

**Issue by mkoskar** [GermainZ/weechat-vimode#32]
I've noticed that with some version of Weechat there is new `/input search_text_here` command which is also a default binding for `Ctrl+R`. Comparing to `/input search_text` it does not scroll buffer to the end but start search on current scroll position. What about making `/` use it too?

```diff
diff --git a/vimode.py b/vimode.py
index 379ebd9..0dff248 100644
--- a/vimode.py
+++ b/vimode.py
@@ -781,7 +781,7 @@ VI_KEYS = {'j': "/window scroll_down",
            'I': key_I,
            'yy': key_yy,
            'p': "/input clipboard_paste",
-           '/': "/input search_text",
+           '/': "/input search_text_here",
            'gt': "/buffer +1",
            'K': "/buffer +1",
            'gT': "/buffer -1",
```

**Comment by GermainZ** [comment]
Sounds good: fc2615d6f7ac454b60ba8771d3a4068effdbf152

Cheers.
