### ISSUE TITLE
Enter (^M) key in NORMAL mode

### ISSUE THREAD

**Issue by mkoskar** [GermainZ/weechat-vimode#33]
I've observed following:

* go inside NORMAL mode
* scroll buffer such that you are not on the end (i.e., there is '-MORE(xy)-' in status bar)
* press `^M` (i.e., Enter key) once
* press any key e.g., `i` (for 'insert') or `k` (for 'up') **— it will be ignored**
* next keys are registered fine

Note: `^J` doesn't have this issue

**Comment by GermainZ** [comment]
b963971781560d95475ec1f969a971c9224cb743 should fix this.
