### ISSUE TITLE
Auto-completion in ex mode

### ISSUE THREAD

**Issue by felixSchl** [GermainZ/weechat-vimode#35]
Thank you for this plugin! Any chance we could get tab-completion in ex mode? Ex mode looks very appealing but would be even more so if I could tab-complete the command I am typing.

**Comment by GermainZ** [comment]
It's something I plan to do eventually, yes.

**Comment by GermainZ** [comment]
e9922b556e97f633dac7fa2415744795115a2ea9 adds partial support for tab-completion of weechat-vimode command names, although full support isn't possible as I can't access the completions provided by WeeChat.

If you have an idea for an alternate implementation, please let me know.
