### ISSUE TITLE
Allow F11/F12 in Normal mode

### ISSUE THREAD

**Issue by BlitzKraft** [GermainZ/weechat-vimode#36]
When in insert mode, scrolling the nicklist works just fine (F11/F12).  In normal mode, they are ignored.

Is it possible to add a list of keys to be completely ignored and allow weechat to react accordingly? Or would it be easier to bind them to the same actions in normal mode?

**Comment by GermainZ** [comment]
>Is it possible to add a list of keys to be completely ignored and allow weechat to react accordingly?

Not possible currently, but I like that idea.

>Or would it be easier to bind them to the same actions in normal mode?

You can do this currently by editing the vimode.py manually if you want. Let me know if you need help.

**Comment by BlitzKraft** [comment]
Yup. I just started looking through the source. Thank you!

**Comment by GermainZ** [comment]
FYI, `nt` and `nT` were added for nicklist scrolling in normal mode, if you want to use those instead.

**Comment by BlitzKraft** [comment]
I am trying to use F11/F12 for nicklist navigation. Their keycodes are 122 and 123 (decimal). 

I don't know how translate(if that is the right word) them to the notation in file (using `\x01[`). 

From what I understand, `\x01` is the byte sequence for Escape key, and `\x01[` is for the Control key. Is that correct?

**Comment by GermainZ** [comment]
Ah, sorry, didn't expect it not to be straightforward (just "F11"). Just checked in weechat and F11 is `meta2-23~` (`alt-k → F11` in Insert mode to check what F11 is bound to and how weechat sees it).

Meta is `\x01`, ctrl `\x01[`, meta2 `\x01[[`, which gives:

- F11: `\x01[[23~`
- F12: `\x01[[24~`

Eventually I hope to add some way for users to define custom key bindings without worrying about the escape sequences (e.g. just "F11", "alt-2", "ctrl-k", etc).

**Comment by BlitzKraft** [comment]
Done!! That fixed it.

Thanks for the additional info!

Regarding the custom key bindings, a function+dictionary, to break the string, and construct the required byte sequence seems sufficient. I will look into doing that.
