### ISSUE TITLE
Last character is being ignored when a command is typed

### ISSUE THREAD

**Issue by BlitzKraft** [GermainZ/weechat-vimode#37]
I have `/ls` aliased to `/buffer list`. When I type this in Normal mode, I get `Error: Unknown command '/l'`

But if I type `lss` or append any character, even a space, it works as if it received `ls`. This only happens on commands that don't take any argument. I have mapped  `/buffer` to `/b` as an alias. When I put in a number (single or a double digit), it works fine. 

This does not happen in insert mode; that is when a command is issued without using vimode. I am not sure what is causing this.

**Comment by GermainZ** [comment]
Are you typing `/ls` or `:ls`?

**Comment by BlitzKraft** [comment]
I am typing `:ls`

**Comment by GermainZ** [comment]
[I can't reproduce this.](https://ptpb.pw/ALEgzXDiRO9RUUWySIlz7W3guMTn.webm)

**Comment by BlitzKraft** [comment]
Here is a screenshot: http://imgur.com/fwp57hd

I also included the warnings for keybindings and other plugins that are loaded along with vimode.

**Comment by GermainZ** [comment]
>EDIT: In the screenshot, I removed `ls` from the alias list

Just to make sure I'm not missing anything, you deleted the `ls` alias?

**Comment by BlitzKraft** [comment]
I removed it from my weechat aliases. Yes.

**Comment by GermainZ** [comment]
Ah, right, you just removed it so it wouldn't spam the output.

1. You're just typing `Esc` → `:ls` → `Return`, correct?
2. What weechat-vimode/weechat versions are you using?

**Comment by BlitzKraft** [comment]
1. That is correct.

2. weechat version 1.3; vimode.py version 0.5.

I downloaded it from the repo (branch: master). I downloaded the just vimode.py; it was less than 12 hours ago that I started using this version. 

Before this, I had it from weechat scripts page. I used the older version very briefly. I don't know if it had the same issue.

**Comment by GermainZ** [comment]
Ah, my mistake. I can reproduce this now -- I was testing with an older version. The issue should now be fixed, thanks!
