### ISSUE TITLE
yy (yank) or paste (p) doesnt seem to work in mac os x 

### ISSUE THREAD

**Issue by arooni** [GermainZ/weechat-vimode#39]
Hey -- love your tool!  VIM inside weechat?  Amazing.

On Mac OS X El Capitan (10.11.6) ;  yank doesn't seem to copy to my clipboard, nor does paste seem to paste anything I just yanked.

Running with weechat 1.5 from homebrew.  Let me know if you need any other things to track this down, or if I'm doing something wrong.

Thanks again!

**Comment by arooni** [comment]
This might help ;  results of me trying the yy command (from the weechat buffer)

031503    | python: stdout/stderr: Traceback (most recent call last):
031503    | python: stdout/stderr:   File "/Users/david/.weechat/python/autoload/vimode.py", line 989, in cb_key_combo_default
031503    | python: stdout/stderr:     VI_KEYS[vi_keys](buf, input_line, cur, count)
031503    | python: stdout/stderr:   File "/Users/david/.weechat/python/autoload/vimode.py", line 598, in key_yy
031503    | python: stdout/stderr:     stdin=subprocess.PIPE)
031503    | python: stdout/stderr:   File "/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
031503    | python: stdout/stderr:     errread, errwrite)
031503    | python: stdout/stderr:   File "/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
031503    | python: stdout/stderr:     raise child_exception
031503    | python: stdout/stderr: OSError: [Errno 2] No such file or directory
031503    | python: error in function "cb_key_combo_default"

**Comment by GermainZ** [comment]
weechat-vimode uses xclip by default. Could you try editing lines 272 and 600 to use something that's available on Macs? Should work if you replace this:

    proc = subprocess.Popen(["xclip", "-selection", "c"],
                            stdin=subprocess.PIPE)

with this:

    proc = subprocess.Popen(["pbcopy"],
                            stdin=subprocess.PIPE)

**Comment by arooni** [comment]
Yup!  That worked great!  

Thanks for such a great edition to weechat; and the quick response time!
