### ISSUE TITLE
Copy/Paste program should be configurable by user

### ISSUE THREAD

**Issue by bartonski** [GermainZ/weechat-vimode#40]
This is essentially a generalization of issue 39; I use `xsel` under linux rather than `xclip`. It would be nice if I could set this via configuration vs. editing `operator_y()` and `key_yy()`.

**Comment by GermainZ** [comment]
The commands used for copying/pasting are now configurable as per b269613906cea33e97ca238b8c0e4882a392e3e8 and c934379f349c87700b4928f8512c8ca3d64ef8c5. Cheers :)
