### ISSUE TITLE
Add :wq to save and close

### ISSUE THREAD

**Issue by tobanw** [GermainZ/weechat-vimode#42]
`:qall` does `/exit`, which doesn't save the configuration. I'd suggest either changing that to `/quit`, which does save and exit, or adding `:wq` as a separate command.

**Comment by bbugyi200** [comment]
It looks like `exit` is just aliased to `quit`, so it should still save the configuration. I did wish that `:qa` was an option though. I added that command and multiple others aliases to existing commands with 01994cde39a84761d0e35033ace58c7794ae52ce.
