### ISSUE TITLE
[feature request] Digraphs

### ISSUE THREAD

**Issue by 4e554c4c** [GermainZ/weechat-vimode#46]
See `:h digraph` in vim.

Digraphs are groups of two characters in vim that can be typed as `CTRL-K {char-1} {char-2}` or, if the `digraph` option is set `{char-1} <BS> {char-2}`.  For example typing `CTRL-K B B` in insert mode leads to the "broken" character: `|`. In vim, new digraphs may be added with the `:digraph` command, but I don't think that that part is as important.
I think that this feature would be rather helpful to those who use non-Latin characters on a Latin keyboard in IRC.

**Comment by GermainZ** [comment]
Wouldn't using the [compose key](https://wiki.archlinux.org/index.php/Keyboard_configuration_in_Xorg#Configuring_compose_key) be a better and more universal alternative?

**Comment by 4e554c4c** [comment]
Yeah, I've started using compose and ibus for foreign input. Sorry about leaving this open
