### ISSUE TITLE
Undo history

### ISSUE THREAD

**Issue by voidzero** [GermainZ/weechat-vimode#47]
Greetings,

Thank you so much for this script. I absolutely love it.

Do you think you could provide undo history? For example, in normal mode, `ra` replaces the current character with an 'a'. It would be great if `u` could be made to undo this, with a history so you can undo more things, and Ctrl+r to redo.

(One more small question: how can I add a key binding to the normal mode? I'd like `meta-a => /input jump_smart` to work in normal mode.)

Much obliged,
Mark

**Comment by aranmohyeddin** [comment]
Oh I just wanted to ask this feature request:))

**Comment by GermainZ** [comment]
Should be possible as of f5e5df3fe2f3ba57faff338f57ff4becf44339c7.
