### ISSUE TITLE
nT and nt for scrolling namelist not working

### ISSUE THREAD

**Issue by ecly** [GermainZ/weechat-vimode#48]
I don't have nT or nt bound for anything else and script "vimode.py" is already installed and up-to-date. Anyone else experience this or know what could be the problem?

**Comment by zsinx6** [comment]
I'm having the same issue

**Comment by ecly** [comment]
@zsinx6 hey, I just found that this is merely due to the weechat supplied version of vimode is outdated. I've just submitted an update on there, but don't know how long it will take. Till then you can manually update the vimode.py file in '~/.weechat/python/' with the contents of the one present in this repo.

**Comment by ecly** [comment]
I'll close the issue once the version in weechat script repos has been updated.

**Comment by ecly** [comment]
@zsinx6 update your weechat scripts - it has been just been [merged](https://github.com/weechat/scripts/pull/251) into the official weechat scripts repo.
