### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by mkoskar** [GermainZ/weechat-vimode#51]
Just noticed minor version mismatch.

While in https://github.com/weechat/scripts it's ``SCRIPT_VERSION = "0.5.1"`` upstream version here is ``SCRIPT_VERSION = "0.5"``. That causes Weechat to think my local -git installation is out-of-date. Marking script with "hold" is fine, just thought I'll point this out.

**Comment by GermainZ** [comment]
Should be fixed with the next update. weechat/scripts#274
