### ISSUE TITLE
Custom <Esc> sequence?

### ISSUE THREAD

**Issue by adtac** [GermainZ/weechat-vimode#52]
In vim, I use `jk` to switch from insert mode to normal mode. I was wondering if that is possible with this plugin? To do this, I do `imap jk <Esc>` in my vimrc.

Awesome plugin, btw!

**Comment by GermainZ** [comment]
Glad you're enjoying it! :)

Mapping keys in insert mode is not currently possible, but support can be added. I'm curious if just adding an option for `jk` is enough, or if I should try and add something more customizable like `:imap`. Are there any other use cases in an IRC client?

**Comment by adtac** [comment]
For me, I only use `jk`, but I assume others use other bindings. For example, I've seen people use `jj` for the same thing.

If it's easier, I think simply allowing custom `<Esc>` remapping (so that both the `jk` and `jj` crowd would be satisfied) would be sufficient for me and for this issue. Implementing `:imap` could be a separate issue since it's bigger and more general.

**Comment by GermainZ** [comment]
Added in 8478d6b1c96bdd57893abc937e0fbaa33bbc702f. It's not used by default, but you can configure it to your liking. :) See plugins.var.python.vimode.imap_esc and plugins.var.python.vimode.imap_esc_timeout.

**Comment by adtac** [comment]
Awesome! Thanks!
