### ISSUE TITLE
Navigation during search

### ISSUE THREAD

**Issue by chrisduerr** [GermainZ/weechat-vimode#53]
In vim it is possible to search using `/text`, this is already possible in this script. However after the search is completed, it's possible to use the shortcuts `n` and `N` to jump between results.

The default keybinds of weechat involve either the ctrl modifier or the arrows, so I think it would be beneficial to introduce a simple and vim-like `n`/`N` navigation to make it possible to jump through the search results with a single key.

**Comment by GermainZ** [comment]
Added in 76e2a03d4d4e29a9247cbd40e03486e689dc33b4, thanks for the suggestion. Please note that it comes with certain limitations due to the way WeeChat works, which is why it's optional and disabled by default.
