### ISSUE TITLE
feature request for j/k/^j/^k to work like ↑/↓/^↑/^↓ in normal mode.

### ISSUE THREAD

**Issue by aranmohyeddin** [GermainZ/weechat-vimode#54]

**Comment by GermainZ** [comment]
See #20

**Comment by GermainZ** [comment]
As of 6c881f0f060a8a2dbb8135d5f1d6db70ca91dda3, this is now possible by executing the following commands while in Normal mode:

```
:nmap j <Up>
:nmap k <Down>
:nmap <C-j> <C-Up>
:nmap <C-k> <C-Down>
```

**Comment by aranmohyeddin** [comment]
so if I add a keymap once it will be permanent? I don't need to add it to a file or something like how we do in vimrc?

**Comment by GermainZ** [comment]
>so if I add a keymap once it will be permanent?

Yes. It's stored in `plugins.var.python.vimode.user_mappings` like a normal WeeChat setting.
