### ISSUE TITLE
vi_search not exactly like vi_search.

### ISSUE THREAD

**Issue by aranmohyeddin** [GermainZ/weechat-vimode#56]
in vim normal mode:
press /
type something
press enter
press n/N
press /
you will end up in a new search but in the search mode of the plugin you have to press enter one more time and then press / again to start a new search.

**Comment by GermainZ** [comment]
This is the "intended" behavior because I don't see a better way to do it otherwise (at least not without reimplementing the whole search logic instead of leveraging WeeChat's).

**Comment by aranmohyeddin** [comment]
there is a state at which if we press n/N we will go to next/previous match. what I mean is that in that case if we press / we reset the search query I think it must be relatively easy to implement. or not?

**Comment by GermainZ** [comment]
Ah, sure. I misunderstood your suggestion.

**Comment by GermainZ** [comment]
00287e8100c903001491d8c8a15394249e471e67 solves this.
