### ISSUE TITLE
feature request for command history.

### ISSUE THREAD

**Issue by aranmohyeddin** [GermainZ/weechat-vimode#57]
I notice that unlike vim and unlike weechat '/' commands there is no "up arrow history" I think it would be very useful. if you think it's not worth to have ctrl+up for global history and up for buffer history, I believe only having the global history is much more useful.

**Comment by GermainZ** [comment]
Do you mean for vimode's command bar (when you press ":" in normal mode), or for Weechat's input bar?

**Comment by aranmohyeddin** [comment]
I mean for command bar to not exist and to commands to be written into
input bar just like search term(after pressing /) and if u think that would
be confusing I think that can be easily handled by just adding an indicator
that would allow a command is being typed rather than a msg being written.

**Comment by aranmohyeddin** [comment]
I mean for command bar.

**Comment by GermainZ** [comment]
Added in b995b50db422fd63551c02dbde8107872abcb957.
