### ISSUE TITLE
Swapping jk and JK results in nothing happening

### ISSUE THREAD

**Issue by eyJhb** [GermainZ/weechat-vimode#67]
If you swap those keys, then it none of them works.

```
python.vimode.user_mappings = "{"k": "K", "j": "J", "K": "k", "J": "j"}"
```

**Comment by GermainZ** [comment]
Are you using the latest version from git (if not, please test with it), or the one in the weechat repo?

**Comment by eyJhb** [comment]
Using latest version - commit 1da5a2e1c02d21bdada2dd76584a824df53bc4de

Fixed it by doing this ...

```
python.vimode.user_mappings = "{"K": "/window scroll_up<CR>", "J": "/window scroll_down<CR>", "k": "/buffer -1<CR>", "f": "/go<CR>i", "j": "/buffer +1<CR>"}"
```

The formatting of that config line defies everything regarding strings btw.

**Comment by GermainZ** [comment]
Just checked it out. It doesn't work because it's a recursive mapping. It should be showing you this error:

> Something's not right. The following user mapping is recursing on itself: ("k", "K")

Is it not showing the above warning for you?
(Trying the same in vim will show you a similar error.)

**Comment by eyJhb** [comment]
Not as far as I could see, it should instead stop one from actually doing it, so you don't end up stuck in something that doesn't work. :)

**Comment by GermainZ** [comment]
Ah, warnings were being printed to the "weechat" buffer. c8ba938f47accf1126006ae612fc30a4520be384 will make them show up in the current buffer, which should be more useful. That should've been the default behavior, but I didn't catch it -- thanks for bringing it up.

**Comment by eyJhb** [comment]
@GermainZ but shouldn't it still block the action, of making such a mapping?
