### ISSUE TITLE
Available on Arch @ AUR

### ISSUE THREAD

**Issue by sQVe** [GermainZ/weechat-vimode#68]
I just wanted to note that I've created and now maintain `weechat-vimode-git` on *AUR*. The package can be found here: https://aur.archlinux.org/packages/weechat-vimode-git/

This enables one of quickly install your script with, for example: `yay -S weechat-vimode-git`.

**Comment by GermainZ** [comment]
Thanks! It would be a good idea to rename it to `weechat-vimode-git`, though.

**Comment by sQVe** [comment]
@GermainZ Yeah, my bad. I'm way to tired. Will fix ASAP.

**Comment by sQVe** [comment]
Fixed naming and updated first post with the correct information. Closing.

**Comment by GermainZ** [comment]
Great, thanks :) I've added a note about it in the README 3a41780165d0cc8ba7c416b0ff64bfffa6f8a550
