### ISSUE TITLE
Possible to bind arrow keys?

### ISSUE THREAD

**Issue by sQVe** [GermainZ/weechat-vimode#69]
Quick question. Is is possible to bind arrow keys, for example `^W-Left`? If so, how?

**Comment by GermainZ** [comment]
(Is that `Ctrl-W` followed by `<Left>`? Does that even work in vim? I can't seem to do it.)

You can use `<Up>`, `<Left>`, `<Right>`, `<Down>`. Some examples:

- `:nmap <Up> /help`
- `:nmap <M-Up> /help`

**Comment by GermainZ** [comment]
Probably an issue with my terminal and ctrl-arrow key combos, then.

`:nmap <C-W><Left> /cmd` should work. :)
