### ISSUE TITLE
Nicer line numbers formatting

### ISSUE THREAD

**Issue by mkoskar** [GermainZ/weechat-vimode#73]
Numbers are usually better right aligned (quick and dirty example bellow).

Line width could be determined from ``bar_height`` but possibly better would be to have a configuration value for it to accommodate user's preference; then 1 (or 0 as Python's default) would render current behavior. 

```diff
diff --git a/vimode.py b/vimode.py
index 55a5f87..4302be2 100755
--- a/vimode.py
+++ b/vimode.py
@@ -1653,8 +1653,9 @@ def cb_line_numbers(data, item, window):
     bar_height = weechat.window_get_integer(window, "win_chat_height")
     content = ""
     for i in range(1, bar_height + 1):
-        content += "{}{}{}\n".format(vimode_settings['line_number_prefix'], i,
-                                     vimode_settings['line_number_suffix'])
+        content += "{}{:2}{}\n".format(vimode_settings['line_number_prefix'],
+                                       i,
+                                       vimode_settings['line_number_suffix'])
     return content
 
 # Callbacks for the line numbers bar.
```

**Comment by GermainZ** [comment]
Agreed. Added in 95661a27f92dc3f3286cf1539ab112a81ad15639, although without a preference. A preference can be added if someone feels strongly about this, but I figured it makes sense and is more consistent with WeeChat in general as well (e.g. buffer numbers, nick alignments, etc). Thanks!
