### ISSUE TITLE
Screencast link in Readme 404s

### ISSUE THREAD

**Issue by lhanson** [GermainZ/weechat-vimode#78]
The screencast link in README.md returns 404. It would be great to have a working screencast to explore the plugin, perhaps https://www.youtube.com/watch?v=tjHEbfwHlR4

**Comment by GermainZ** [comment]
Seems I've lost the original screen recording, unfortunately.

@gotbletu would you mind if I linked to your [video demo](https://www.youtube.com/watch?v=tjHEbfwHlR4) in the README?

**Comment by gotbletu** [comment]
Sure go ahead. Thanks for choosing my video =)

**Comment by GermainZ** [comment]
Thanks! 6412084ae263a75790b8ea6fb36c75a7eb06c16b
