### ISSUE TITLE
Toggle nicklist

### ISSUE THREAD

**Issue by sQVe** [GermainZ/weechat-vimode#81]
Hey :wave:,

It would be awesome to have a command or binding to toggle the nicklist. I do not enable the nicklist by default and I know that there are plenty of other users that also does this. This makes it a bit awkward when you need to nicklist because you need to go to **INSERT** mode and toggle it with a weechat binding.

**Comment by GermainZ** [comment]
You can define a custom key binding to do so for now, for example:

```
<Esc> (to enter Normal mode)
:nmap zn /bar toggle nicklist
```
