### ISSUE TITLE
Current master version doesn't load in weechat 2.9 / MacOS

### ISSUE THREAD

**Issue by normen** [GermainZ/weechat-vimode#86]
I had the current master version of the plugin installed in weechat 2.8 on MacOS, updated weechat via brew to 2.9, now the plugin doesn't seem to be active anymore. The script window shows the plugin as installed but it doesn't do anything. Installing the version from the scripts repository works.

Edit: Seeing no errors on startup.

**Comment by GermainZ** [comment]
e04b32fdf923cc4eb2b8ee98e291905693a25bd9 should fix this, thanks for reporting.

**Comment by normen** [comment]
Yep, loading again, thanks!
