### ISSUE TITLE
Combining commands in binds using <CR> doesn't work in weechat 2.9

### ISSUE THREAD

**Issue by normen** [GermainZ/weechat-vimode#87]
Since the /window scroll_up was a bit too slow for me I did a mapping for Ctrl-U / Ctrl-D looking like `/window scroll_up<CR>/window scroll_up<CR>/window scroll_up<CR>` and it worked a treat in weechat 2.8

Now in 2.9 the mapping results in an error message from weechat saying "Error occurred with command".

**Comment by GermainZ** [comment]
The custom binding works for me (tested with `:nmap <C-U> /window scroll_up<CR>/window scroll_up<CR>/window scroll_up<CR>`).

That being said, I would suggest just changing the value of `weechat.look.scroll_amount` and removing the custom bindings using `:nunmap <C-D>` and `:nunmap <C-U>`.

**Comment by normen** [comment]
Right, it works in the master version, it does _not_ work in the script repo version - sorry, didn't think about me changing to that version.
