### ISSUE TITLE
Abnormal behavior for : on launch

### ISSUE THREAD

**Issue by danisztls** [GermainZ/weechat-vimode#90]
The first time `:` is pressed, after launching, Weechat it will enter Insert mode instead of Command. That may cause commands to be sent as messages to channels.

**Comment by GermainZ** [comment]
I can't reproduce this with WeeChat 3.1 and the git version of weechat-vimode.

**Comment by danisztls** [comment]
Thanks. I am using Weechat 3.1 and the git version of vimode. I guess it was my configuration them.
