### ISSUE TITLE
Artifacts on command and search

### ISSUE THREAD

**Issue by danisztls** [GermainZ/weechat-vimode#91]
Pressing `/` will enter search mode but the issuing character will not be ignored or automatically deleted and require the user to manually delete it.

With command mode the same happen but it is expected. But if the user would press ESC to cancel the command the input bar would not be cleared of the issuing `:`.

**Comment by GermainZ** [comment]
I can't reproduce this with WeeChat 3.1 and the git version of weechat-vimode.

**Comment by danisztls** [comment]
Thanks. I am using Weechat 3.1 and the git version of vimode. I guess it was my configuration them.

**Comment by bfrg** [comment]
I'm having the same issues and don't know how to solve it.
